spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/fmmall2?characterEncoding=utf-8&autoReconnect=true&useUnicode=true
      username: root
      password: 20020222pxp
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: always
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.example.fmmall.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
